Move rumble files to CMSMonit from CMSKubernetes
dmwm/CMSMonitoring pull request #105
Opened 2020-11-23 21:49 UTC by mrceyhun

@vkuznet 
Rumble related non-k8s related files moved to CMSMonitoring.

2020-11-23 22:10 UTC, mrceyhun commented
I used tab in python code, pep8 saw it okay. According to your suggestion, I changed it to 4 spaces now.

2020-11-23 23:29 UTC, vkuznet requested changes
Please fix default urls, everything is ok.

2020-11-23 23:29 UTC, vkuznet commented on src/go/Rumble/rumble.go
> +	defaultUrl := "http://test-cluster-jnbxujghdusq-node-0.cern.ch"
please use https://cms-monitoring.cern.ch as default url in the code, in your tests you can use whatever url you want.

2020-11-23 23:29 UTC, vkuznet commented on src/python/Rumble/rumble.py
> +        default_url = "http://test-cluster-jnbxujghdusq-node-0.cern.ch"
please use https://cms-monitoring.cern.ch as default url

2020-11-24 00:05 UTC, mrceyhun commented
@vkuznet 
I rebased upstream after last merge and applied your requested changes.

2020-11-24 12:49 UTC, merged