Improve rucio-dataset-mon-go with embed
dmwm/CMSMonitoring pull request #148
Opened 2022-06-17 21:41 UTC by mrceyhun

- Now serves both api requests and static (index.html) file. index.html file calls /api/datasets and get results
- Full test data imported to Mongo, can be used for test
- DataTable arranged
- dataset controller is fixed
- GH workflow is added to build the image

Deployed to cmsweb test1 cluster under `-n cmsmon-mongo` . Sorry for the go format, I forgot in the previous PR.

To-Do:
- I know there is a hardcoded URL in ajax call, which is a working deployment; it will be changed after setting ingress/traefic configuration
- Environment variable and secret usage is getting complicated. I'll solve this problem by creating a common secret and reading all credentials from there. For now, this implementation is working.
- DataTable(index.html) needs a lot of improvements

**Main idea about the final product:**
Main page will only show general dataset informations.  There will be multiple MonggoDB collections:
- datasets : contains RSEs that a datasets resides, min/max/total size in RSEs, access/create times
- rse-details: contains dataset info for each RSE, similar to [Show Details](https://cmsdatapop.web.cern.ch/cmsdatapop/rucio_datasets/disk/datasets_never_read.html) values in static html pages
- accounts-rules: contains accounts and rules of a specific dataset in a RSE. A button will list them in the page
These collections data will be used in the Show Details part. They will be joined and aggregated, then provided as html part for each dataset. Each collection requires very complex Spark job. Apart from Spark job, we need JavaScript and Go implementations.

Any help, idea, suggestion is welcomed.

fyi @dynamic-entropy

2022-06-18 15:24 UTC, vkuznet requested changes
@mrceyhun , you have recurrent pattern like this
```
log.Printf("[ERROR] Request body read failed %s", err)
		c.JSON(http.StatusInternalServerError,
			responses.DtErrorResponse{
				Status:  http.StatusInternalServerError,
				Message: "Request body read failed",
				Data:    map[string]interface{}{"data": err.Error()},
			})
```
It happens three times already. So make it as function which will take two arguments, a message and error, e.g.
```
func errorJSON(c *gin.Context, msg string, err error) {
                log.Printf("[ERROR] %s %s", msg, err)
		c.JSON(http.StatusInternalServerError,
			responses.DtErrorResponse{
				Status:  http.StatusInternalServerError,
				Message: msg,
				Data:    map[string]string{"data": err.Error()},
			})
}
```
and, then use this function in all places where this pattern occurs

2022-06-18 15:24 UTC, vkuznet commented on src/go/rucio-dataset-mon-go/controllers/dataset_controller.go
> +				Data:    map[string]interface{}{"data": err.Error()},
this should be `map[string]string` as `err.Error` returns the string

2022-06-18 15:24 UTC, vkuznet commented on src/go/rucio-dataset-mon-go/configs/env.go
> +	log.Println("Mongo uri")
can you make one log ling here instead of two.

2022-06-18 15:24 UTC, vkuznet commented on src/go/rucio-dataset-mon-go/controllers/dataset_controller.go
> +					Data:    map[string]interface{}{"data": err.Error()},
use `map[string]string`

2022-06-18 15:24 UTC, vkuznet commented on src/go/rucio-dataset-mon-go/controllers/dataset_controller.go
> +				Data:    map[string]interface{}{"data": err.Error()},
again, please use `map[string]string`

2022-06-18 15:24 UTC, vkuznet commented on src/go/rucio-dataset-mon-go/controllers/dataset_controller.go
> +				Data:    map[string]interface{}{"data": err.Error()},
again the same patter for map and returninig message.

2022-06-18 15:24 UTC, vkuznet commented on src/go/rucio-dataset-mon-go/controllers/dataset_controller.go
> +					Data:    map[string]interface{}{"data": err.Error()},
again,  map and return patterns

2022-06-18 15:24 UTC, vkuznet commented on src/go/rucio-dataset-mon-go/controllers/dataset_controller.go
> +					Data:    map[string]interface{}{"data": err.Error()},
again map and return patterns

2022-06-18 15:24 UTC, vkuznet commented on src/go/rucio-dataset-mon-go/main.go
> +
Please add into main option to provide server version and info. see https://github.com/dmwm/dbs2go/blob/master/main.go#L21, then add makefile which will setup `gitVersion`, see https://github.com/dmwm/dbs2go/blob/master/Makefile#L2, and add new end-point which will return server info, see https://github.com/dmwm/dbs2go/blob/master/web/handlers.go#L284 Such that someone can query your server and get the info, e.g.
```
scurl https://cmsweb.cern.ch/dbs/prod/phys03/DBSReader/serverinfo
[{"dbs_version":"v00.05.32","server":"dbs2go git=v00.05.32 go=go1.18.3 date=2022-13-06"}]
```
As you can see it is very useful to know from the server itself which version it is running

2022-06-19 01:25 UTC, mrceyhun commented
Thanks a lot for the review @vkuznet 

- `/serverinfo` is implemented. The version should be the git tag but now it shows the last tag of the repo. The test docker image was not built using git tag, that's why it shows latest tag of the repo. I.e.:
```
$> /cvmfs/cms.cern.ch/cmsmon/gocurl \
    -u http://cmsweb-test1-zone-b-brkegglzfmze-node-1.cern.ch:31280/serverinfo \
    -k ~/.globus/userkey.pem -c ~/.globus/usercert.pem 
 {"version":"go-0.5.39-8-g88ecff5","server":"rucio-dataset-mon-go git=go-0.5.39-8-g88ecff5 go=go1.18.3 date=2022-19-06"}
```
- Error json response is put into function and it's used in repeating places.
- `map[string]string` is implemented for `err.Error()` string.

Additionally:
- Routers are arranged into single main one.
- `Makefile`, `LICENSE` and documentation files added. 
- README.md is arranged to include `goreportcard` and `godoc`. All inspired by `dbs2go` and previous PR comment.

2022-06-19 12:19 UTC, vkuznet approved these changes

2022-06-19 13:49 UTC, merged